R/diagnostics.R
Identify style or warning like RStudio output(https://github.com/jimhester/lintr#rstudio)
=> Fix lintr output

README.md
I just tried this with Emacs + ESS, with great success. This PR documents the configuration needed for Emacs integration.
=> Provide settings needed for Emacs

R/formatting.R
=> Fix formatting empty file

R/document.R
This PR is an initial attempt to address #55 by implementing recursive parsing of a document so that symbols in the global scope would be added to the completion list.
As for function definition range, since R's `parse()` only provides document ranges of top-level expressions, so that non-top level functions defined will share the same definition range at the moment.
=> Recursive parsing

R/document.R, R/log.R
This PR fixes #64 by explicitly checking length of variables for safety.
=> Fix crash on empty file

R/log.R
Fix the case where `x` may not be `character`.
=> Fix to_string()

R/formatting.R, R/languagebase.R, man/style_text.Rd, tests/testthat/test-formatting.R
@renkun-ken 
Does it sound too restrictive? Range formatting won't work unless the user selects carefully. Any partial highlight won't result in formatting.
close #67
=> check if the selection contains complete lines

.github/workflows/main.yml, R/utils.R, tests/testthat/test-completion.R
=> match the leading dot

R/document.R
=> Check missing e in parse_expr

R/completion.R, R/workspace.R
This PR expands completion item resolve to constants so that their documentation is also provided in completion. Then all types of completion items are covered.
=> Resolve completion item of constants

R/completion.R, R/definition.R, R/hover.R
=> Fix function xpath

src/reader.c
=> fix buffer overflow error

R/formatting.R
=> Fix typo in range_formatting_reply

DESCRIPTION
If there are no major bugs found, a new version will be released next week as a X'mas 🎁. Cheers.
cc: @renkun-ken
=> v0.3.3 candidate release

R/languageserver.R
=> use writeLines to write raw data in Windows

R/link.R
This PR follows up #171 and fixes:
* Provide document link to absolute paths
* Only provide document link if file exists and if path is not directory
=> Fix handling directory and absolute path in document_link_reply

R/languageserver.R
attempt to fix #170
@takuizum, could you pull this and give it a try?
=> make sure utf8

R/diagnostics.R, R/document.R
=> Handle empty content in parse_document

DESCRIPTION, R/document.R, R/handlers-langfeatures.R, R/handlers-textsync.R, R/languageclient.R, R/languageserver.R, R/link.R, R/symbol.R, R/task.R
=> some lsp clients may not send textDocument/didOpen

R/protocol.R
=> make sure NULL converts to json's null

README.md
Suggested by https://github.com/REditorSupport/languageserver/issues/141#issuecomment-584323875.
=> Add instructions to enable formatting cache to README

R/diagnostics.R
Closes #218 
When `diagnostics_task` fails, it still calls `diagnostics_callback` to report that diagnostics failed so that user would know there's problem in the file to cause lintr to fail (such as https://github.com/jimhester/lintr/issues/461).
Also, the diagnostics result previously uses `source = "lintr"` which is not so informative, now it's changed to `source = result$linter` so that user would know which linter produces this result. If user finds it not helpful, user could disable unwanted linters accordingly by customizing default linters.
=> Call diagnostics_callback on diagnostics_task error

R/diagnostics.R
=> Respect linter_file in diagnostics

R/document.R
fix a typo and a misalignment bug.
=> fix enclosed_by_quotes

R/completion.R
=> experiemental setting to disable snippets

.github/workflows/main.yml, DESCRIPTION, R/languagebase.R, R/languageclient.R, R/languageserver.R, R/namespace.R, R/task.R, R/workspace.R
`collections` 0.3.0 follows the tidyverse convention to use small cased function names.
=> requires collections 0.3.0

R/completion.R, tests/testthat/test-completion.R
=> Non export functs

R/namespace.R, tests/testthat/test-completion.R
=> Remove duplicate symobls in completion of workspace symbols

.github/workflows/tagbot.yml, DESCRIPTION
time to release v0.3.6
@renkun-ken do you have anything to add to the coming release?
I have been working on a [package](https://github.com/RTagBot/tagbot) that tags GitHub release automatically. Let see if it would work :)
=> bump to 0.3.6

R/formatting.R
Follow up #268 #269 
Close #270
=> Indent all elements except braces in apply_initial_indention

R/languageclient.R
it maybe the cause of the recent CI failures
=> make sure process is alive

.github/workflows/main.yml
fix the recent mac os build failures
=> use mac.binary instead of mac.binary.el-capitan

R/diagnostics.R
Close https://github.com/Ikuyadeu/vscode-R/issues/376.
This PR drops the diagnostics results if the file is closed.
=> Check uri in diagnostics_callback

R/color.R, R/link.R
=> Try parsing string in link and color

R/utils.R, tests/testthat/test-symbol.R
=> Fix rmd chunk pattern

.github/workflows/coverage.yml, .github/workflows/main.yml, .travis.yml, R/session.R, tests/testthat/helper-utils.R
=> fix covr test

R/completion.R, R/hover.R, R/utils.R
This PR contains some minor improvements:
1. Simplify some string manipulation.
2. Add hover to package symbol.
=> Minor improvements

R/completion.R
=> Only provide imported completions without package

.github/workflows/main.yml, DESCRIPTION, R/completion.R, R/document.R, R/hover.R, R/signature.R, man/arg_completion.Rd, tests/testthat/test-completion.R, tests/testthat/test-hover.R
This PR implements local function support for the following providers:
Screencasts
* Signature
* Hover on function name
* Hover on function argument
* Argument completion
* Scope completion documentation
=> Local function support

R/completion.R, tests/testthat/test-completion.R
=> Fix arg completion

R/namespace.R
Close https://github.com/REditorSupport/vscode-r-lsp/issues/62.
=> Add comment of notice above temp code of definition

NEWS.md, tests/testthat/test-stdio.R
Not sure if it is related. But the failure was around this place.
close #357
=> skip stdio test on solaris

R/capabilities.R, R/handlers-langfeatures.R, R/languageserver.R, R/selection.R, README.md, tests/testthat/helper-utils.R, tests/testthat/test-selection.R
This PR implements [selectionRange](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_selectionRange) provider.
=> Implement selectionRangeProvider

DESCRIPTION, tests/testthat/helper-utils.R, tests/testthat/test-call-hierarchy.R, tests/testthat/test-codeunits.R, tests/testthat/test-color.R, tests/testthat/test-completion.R, tests/testthat/test-definition.R, tests/testthat/test-folding.R, tests/testthat/test-formatting.R, tests/testthat/test-highlight.R, tests/testthat/test-hover.R, tests/testthat/test-langauagecilent.R, tests/testthat/test-link.R, tests/testthat/test-lintr.R, tests/testthat/test-null-root.R, tests/testthat/test-references.R, tests/testthat/test-rename.R, tests/testthat/test-search.R, tests/testthat/test-selection.R, tests/testthat/test-signature.R, tests/testthat/test-stdio.R, tests/testthat/test-symbol.R
This PR adapts the test files to testthat 3.
=> Full testthat v3 compatibility

.lintr
Driving by, I noticed a missing space that bothered me.
=> fix missing whitespace

R/signature.R, R/utils.R
Closes #417 
This PR follows up #371.
=> Fix null doc_string in signature

R/languageserver.R, R/log.R
=> output text as is

R/completion.R
=> `completionItem/resolve` always returns `completionItem`

R/formatting.R, R/utils.R, tests/testthat/test-formatting.R
Closes #224 
Closes #507 
This PR checks scope in rmd document in on type formatting.
=> Check rmd scope in on type formatting

README.md
…which has LSP support built in beginning with version 14.0 (and support for the R language server is preconfigured).
=> Added an entry for BBEdit

R/languagebase.R, R/languageclient.R, R/languageserver.R, R/session.R
Closes #551 
See https://r6.r-lib.org/articles/Introduction.html#finalizers.
=> Use private finalizers for R6 classes

README.md
They update the README, and have pkgdown site now.
=> Update link to the lintr package

R/utils.R
=> Use lua-filter when pandoc_version >= 2.11

R/namespace.R
=> Ignore error on checking is.function of namespace objects

src/reader.c
https://cran.r-project.org/web/checks/check_results_languageserver.html
=> fix CRAN check warnings

.Rbuildignore, DESCRIPTION, NEWS.md
Let's make a new year release.
=> bump to 0.3.15

DESCRIPTION
As used here:
https://github.com/REditorSupport/languageserver/blob/a1af1ca0c76fe9f50c2d57b56159fed0821fef19/R/document.R#L297
=> Include pacman Suggests dependency in DESCRIPTION

R/utils.R
This PR makes `path_from_uri` handle uri like `vscode-notebook-cell://` so that the lintr diagnostics could work properly with R code cells in juypter notebooks in vscode as reported at https://github.com/REditorSupport/vscode-R/issues/1198.
=> Handle vscode-notebook-cell in `path_from_uri`

DESCRIPTION, NEWS.md, README.md
=> bump to v0.3.16

.lintr, R/diagnostics.R
Closes https://github.com/REditorSupport/vscode-R/issues/1482
=> Check path in diagnose_file
