REditorSupport/languageserver

R/completion.R
1. Use `startsWith` in vectorized way and `lapply` for higher efficiency
2. Fix error when typing `for (i` in editor which causes the following error:
```
[Error - 11:12:35 PM] Request textDocument/completion failed.
Message: non-character object(s)startsWith(names(args), token)
Code: -32603 
```
=> Use more effecient methods to construct completions

DESCRIPTION
I was happy to learn about styler being used in this project 😊. In https://github.com/r-lib/styler/issues/396, a user of your project mentioned that styler fails if Windows style EOL characters are used. We have decided to not support Windows style EOL at the moment, but instead ask the user to use Unix style EOL if they want to use styler. Windows style line endings now throw an informative error message with version `v1.0.2`. Hence, I suggest you make this minimal version requirement for the dependency styler.
=> Require latest styler release for more informative error message

R/definition.R, tests/testthat/test-definition.R
Fixes #41 
I added a unit test to `test-definition.R` that simulates two functions being simultaneously removed from a file. It fails when run with the pre-PR version of `definition.R`, as expected based on #41. It passes when run with the PR version of `definition.R`.
=> fix handling of multiple function removal from files

R/languageserver.R
This PR fixes #50 so that non-ascii characters can be correctly handled.
=> Transfer content in bytes to support non-ascii characters in document

R/document.R, R/languageclient.R, R/languageserver.R, R/log.R, R/utils.R, R/workspace.R
This PR uses native functions such as `nzchar`, and `lengths`, and uses safer and faster `vapply` instead of `sapply` in R code.
=> Use native functions

R/log.R
`error` is usually a list of vectors including `message` and `call`, which violates the `vapply` check for `character(1)`.
=> Fix to_string for error case

R/log.R
Passing objects such as `environment` to `to_string()` causes error since `jsonlite::toJSON` cannot handle it.
This PR fixes this by directly using the printing content of non-atomic, non-list objects.
=> Fix to_string for handling complex objects

R/completion.R, man/become_orphan.Rd
Closes #83.
At `::`, workspace symbols are excluded and only package exported objects appear in the completion so that any choice would not refer to a non-existing object.
=> Only provide package exported objects at ::

DESCRIPTION, R/completion.R, R/document.R, R/handlers-textsync.R, R/languageserver.R, R/workspace.R, man/parse_document.Rd, man/workspace_sync.Rd
This is an initial attempt to address #57 using `xmlparsedata` and XPath selectors.
To provide completions in each local scope, all enclosing scopes are detected (except for the top-level). In each of them, all symbols in the assignment expression (`<-`, `->`, and `=`) and function formals in each of these enclosing scopes are collected as locally available symbols at the current position.
The following images demonstrates the scope completions:
One thing yet to improve is that adding new lines to document or removing lines from document make parsed document out-of-sync, so that the line positions are out-of-sync. We should consider parse documents more frequently (i.e. trigger by adding/removing lines) without loading packages (which is the main overhead. parsing is very fast in most …
=> Initial implementation of scope completion using xpath

R/completion.R, R/workspace.R
Closes #81 
This PR uses `find.package(pkg, quiet = TRUE)` to detect if a package is installed in `workspace$get_namespace()` and `workspace$get_code()` so that they may return `NULL` if the requested package is not installed. And subsequent calls to them ignores the case where package is missing so that writing and hovering on an non-installed package (e.g. `abc::`) in the code does not trigger extra logging to notice user that the package is not installed (in vscode the bottom panel jumps to extension logging, which is annoying).
=> Ignore missing packages in completion and definition

R/completion.R
This PR moves `constant_completion` and `scope_completion` to work only in non-package completion, to fix the following cases:
=> Fix completion

R/completion.R
`for` symbol in enclosing scopes are added to the completion.
=> Add for symbol to scope completion

R/completion.R, R/namespace.R, R/workspace.R
Closes #99.
This PR adds `lazydata` in package to `Namespace` and completion. Since `lazydata` is not part of package exports, I use a separate field `lazydata` in `Namespace` rather than combine it with `exports` to respect how these objects are organized in R namespace.
=> Add lazydata to namespace and completion

R/completion.R, R/hover.R, R/signature.R, R/utils.R, R/workspace.R, tests/testthat/test-completion.R, tests/testthat/test-hover.R, tests/testthat/test-signature.R
This PR is an attempt to address #108.
A documentation extractor is implemented and function description is provided in signature, and argument description is provided in arg completion.
Originally, I wanted to provide `ParameterInformation` also in signature. But it's hard to determine which argument is the active parameter due to the complexities of R function argument matching.
=> Add documentation text to signature and arg completion

R/namespace.R, R/signature.R, R/utils.R, tests/testthat/test-completion.R
Since primitive functions do have `args()` output, we can provide their signature.
=> Provide signature for primitive functions

R/document.R, R/namespace.R
Primitive functions like `function` itself has `NULL` args. No need to provide signature for such functions.
=> Check args in get_signature

R/namespace.R, R/workspace.R
This PR addresses #58 by modifying the mechanism of populating the global namespace. One extreme is to infinitely expand global namespace (current approach), the other extreme is to provide completion per document. This PR is an attempt to strike a balance so that global namespace is not infinitely expanding but still shares symbols between multiple documents.
The current mechanism merges objects from parse data on each workspace update. Even if a symbol is removed from all documents, the symbol still lives in the global namespace.
Storing `parse_data` of each `uri` separately and combine them on each update will remove symbols that are removed in documents, making global namespace consistent with documents.
=> Store parse_data separately and combine them in GlobalNameSpace

R/completion.R, R/definition.R, R/hover.R
This PR fixes the issue found at https://github.com/REditorSupport/languageserver/issues/129#issuecomment-565307510.
Now `bar` in the following code can be correctly identified in hover, definition and completion.
```r
bar <- 0
foo$bar <- 1
foo$bar = 1
bar
```
=> Fix XPaths to detect assignments

R/definition.R, R/document.R
This PR is a simple fix of #129.
Highlight will not be provided for the following cases:
* Symbols following `$` or `@`, e.g. `zoo` in `foo$zoo` and `foo@zoo`.
* Function parameter names, e.g. `foo` in `list(foo = 0, bar = 1)`
I'll probably come back later to improve the semantics of highlight.
=> A simple fix of highlight

R/document.R
Closes #132.
Now `parse_document` only returns `env` when the document is successfully parsed, or otherwise `NULL` is returned. Then in `parse_callback`, if it receives `NULL` then it wouldn't call `update_parse_data` so that the existing parse data is preserved to provide functionality for the syntactically incorrect document at the moment.
=> Preserve parsed data when document parsing fails

R/utils.R
A minor change. We should always prefer `if` to `ifelse` unless we need to handle vectors.
=> Use if instead of ifelse

R/document.R, src/languageserver.c, src/search.c, tests/testthat/test-search.R
Fix #135 
PS: note that we stop searching up when an empty line is reached for performance.
=> handle unbalanced closing brackets

src/search.c
The current implementation will give a false alarm if there is an unbalanced open parenthesis in a multiline string.
```r
"
system.time(
"
|
```
We are being conservation here to prevent false alarm in the case of multiline strings. I reckon that it doesn't affect any daily use because multiline strings are not common, especially inside a function call. Secondly, there is always a better presentation of code.
Instead of
```
foo("
some
multiline
string
")
```
The code should be refactored as
```
SOME="
some
multiline
string
"
foo(SOME)
```
=> break find_unbalanced_bracket when a multiline string is encountered

DESCRIPTION, NAMESPACE, R/completion.R, R/definition.R, R/highlight.R, R/hover.R, R/languageserver.R, R/namespace.R, R/signature.R, R/utils.R, R/workspace.R
Closes #148 
Closes #150 
Closes #151
Related #125 
This PR:
* Extends `Namespace` to distinguish exports, functions and non-functions to support signature and definition of all functions in packages.
* Extends `:::` to access all objects in a `Namespace` to be consistent with R (`:::` could access both exported and unexported objects except lazydata)
* Fixes definition and hover of `foo::bar` and `foo:::bar` when `bar` is also definied in `GlobalNameSpace`.
* Fixes all `::` and `:::` access in signature, hover, and definition so that `::` is not able to access unexports, and `:::` is able to access all objects.
* Remove `glue` dependency and use a much simplified version with 15x performance.
* Fixes `workspace$get_documentation` to be able to handle name collision.
=> Extend Namespace with more detailed categories

README.md
Thank you for this precious language server (it became a necessity)! Please consider this update to readme which adds a link to our jupterlab-lsp extension so that they can start using this server with JupyterLab smoothly (or disregard if you think that it does not fit here - I understand that this might be a list of editors that you intend to support, rather than of all clients which support this language server).
Note: we provide automatic configuration, so no config is required.
=> Update README.md: add JupyterLab client

R/capabilities.R, R/formatting.R, R/handlers-langfeatures.R, R/languageserver.R, README.md
This PR is an initial attempt to handling `textDocument/onTypeFormatting` as suggested in #152.
As a starting point, only single line of code is formatted at the moment.
I test this while I'm editing large scripts and the performance is good.
=> Provide textDocument/onTypeFormatting

R/highlight.R
This PR prevents non-word tokens from being highlighted. Currently, the highlight provider would highlight `(`, `<-` and many other operators.
=> do not highlight non-word tokens

R/hover.R
Originally, we use the following format in the hover of a function parameter.
```
`param`: doc string
```
It seems to look better if we change `:` to `—` which is used by TypeScript LSP in VSCode in function parameter hover:
```
`param` — doc string
```
Before
After
=> Change separator between param and doc string in hover

R/capabilities.R, R/handlers-langfeatures.R, R/languageserver.R, R/link.R, README.md
This PR implements `documentLinkProvider` using `STR_CONST` tokens provided by XML parsed document.
=> Implement DocumentLinkProvider

R/completion.R
Closes #167.
This PR:
* Insert `()` after function name when function completion item is selected
* Insert ` = ` after argument name when arg completion item is selected.
=> Insert parentheses to function completion and equals to arg completion

R/handlers-langfeatures.R, R/symbol.R
Closes https://github.com/REditorSupport/languageserver/issues/160
Closes https://github.com/Ikuyadeu/vscode-R/issues/76
Closes https://github.com/Ikuyadeu/vscode-R/pull/193
This PR is a simple support of code section using DocumentSymbolProvider. It matches all commend lines that starts with # and ends with at least four #, +, -, = and show the string in-between as symbol.
This also addresses the comment at https://github.com/Ikuyadeu/vscode-R/issues/76#issuecomment-575969263 by using unified document symbol provider (all in languageserver), and the symbol information of each code section starts from the first line and ends before the next code section so that a hierarchy of code section containing symbol definitions can be presented.
Following is a screenshot in VSCode:
=> Code section support

R/completion.R, R/definition.R, R/diagnostics.R, R/document.R, R/handlers-textsync.R, R/highlight.R, R/hover.R, R/languageserver.R, R/link.R, R/workspace.R
Related to #173 
`Document` and `parse_data` now got `version` so that the sync state (or consistency) could be checked.
When document is open (`textDocument/didOpen`) or modified (`text_document_did_change`), `Document$version` will be updated. A while later when parse task is finished, `parse_data$version` will be updated to `Document$version`. Before parse callback, there would be `Document$version > parse_data$version` so that providers could know that `parse_data` is out-of-sync.
=> Add version to Document and parse_data

R/handlers-langfeatures.R, R/link.R
According to https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize, `rootPath` is deprecated. This PR uses `rootUri` instead of `rootPath`.
=> Only use rootUri in document_link_reply

R/utils.R
Closes #178 
The error is caused by `path_from_uri` and `path_to_uri` not working with `character(0)` input.
Both functions are fixed by checking if input `path` or `uri` has zero length. If so, an empty character vector is returned, which is consistent with the behavior of `file.path`:
```r
file.path(NULL)
file.path(character(0))
```
both return `character(0)`.
=> Fix handling empty input of path_from_uri and path_to_uri

R/languagebase.R, R/languageserver.R, R/log.R, R/utils.R
Closes #180 
This PR:
* Implements `tryCatchStack(expr, ...)` which is an enhanced version of `tryCatch(expr, ...)` to also capture stack trace on error.
* Replace all `traceback()` calls (which do not work with caught error) with `tryCatchStack` so that the logging could properly show the calling stack on error.
Now the error logging includes a stack trace like the following:
It makes it much easier to track down the error.
=> Use tryCatchStack to caputure stack on error

R/document.R, R/handlers-langfeatures.R, R/handlers-textsync.R, R/languageserver.R, R/link.R, R/symbol.R
Closes #173 
This PR implements a simple mechanism that delays `textDocument/documentSymbol` and `textDocument/documentLink` to the time when document `parse_data` is updated in `parse_callback`.
`document_symbol_reply` and `document_link_reply` are refined so that it returns `NULL` if `parse_data$version` does not match `document$version` in the first place. Then the request handler will push the request id, document version, and params to the corresponding reply queue, waiting for `parse_callback` for that `document$version` is done. When `parse_callback` is called, it will handle all queued replies by replying empty response to outdated requests and recall the request handler with stored `id` and `params` for the queued reply that matches the document version.
Under such mechanism, …
=> Reply documentSymbol and documentLink when document parsed

R/symbol.R
Follows up #163 
Closes https://github.com/Ikuyadeu/vscode-R/issues/218
This PR extracts existing code section support for R script to `get_r_document_section_symbols` and implements `get_rmd_document_section_symbols` for R markdown document.
It finds all lines starting with hashes as markdown title and excludes those inside a code block or the front matter in the beginning.
The sections are hierarchical and also include function definitions in Rmd code blocks.
Screenshot in VSCode:
=> Code section support for R Markdown

R/symbol.R
Closes #188 
This PR uses lazy matching (which requires `perl = TRUE`) in the regex that extract code section symbols from both R document and Rmd document.
=> Fix section symbols

R/handlers-langfeatures.R, R/handlers-textsync.R, R/languageserver.R, R/namespace.R, R/workspace.R
Inspired by https://github.com/REditorSupport/languageserver/pull/187#discussion_r375604801 as `environment` has memory leaks as described at https://github.com/r-lib/fastmap#memory-leak-examples, this PR moves the following data from `environment` or `list` to `collections::Dict`
* `LanguageServer$documents(uri)`
* `Workspace$namespaces(pkgname)`
* `Workspace$documentation(name)`
* `Workspace$parse_data(uri)`
=> Move data from environment to Dict

R/capabilities.R, R/color.R, R/handlers-langfeatures.R, R/languageserver.R, README.md
This PR adds support for `textDocument/documentColor` and `textDocument/colorPresentation`.
=> Support textDocument/documentColor and textDocument/colorPresentation

src/languageserver.c
On Windows, R does not read/write bytes content correctly for stdin/stdout. So content-length header is not handled for many Language Server Clients. This change set O_BINARY to stdin/stdout.
=> set O_BINARY for stdin/stdout

README.md
- Remove setting example for Emacs lsp-mode because the upstream now has
it.
https://github.com/emacs-lsp/lsp-mode/pull/1182
=> Remove setting example for Emacs lsp-mode

R/diagnostics.R, R/document.R, R/namespace.R, R/task.R, R/workspace.R, man/parse_document.Rd
PR #204 tries to improve the performance of `parse_task` by avoiding unnecessary loading packages.
However, parsing is always fast while resolving packages with child R session is expensive. We should separate package resolving from parsing so that `parse_task` could callback quickly to provide necessary parse data for all other providers that need it and `resolve_task` should be created only when `parse_data$packages` is changed.
So the task flow looks like:
```
didOpen, didChange, didSave
* diagnostics_task -> diagnostics_callback
* parse_task -> parse_callback
? resolve_task -> resolve_callback
```
Another problem #204 has is that incremental resolving package could not handle reorder of package attaching, so the masking could be incorrect. The safe way to do is that whenever the …
=> Separate resolve task from parse task

R/document.R, R/formatting.R, R/utils.R
Closes #208 
This PR enhances the current implementation of on-type-formatting handler which only tries to format the single-line under editing.
Parsing a short chunk of code without generating source reference is super fast, which allows us to use `parse(text = ., keep.source = FALSE)` repeatedly to find the parse-able expression before current line to perform formatting.
Currently, only `)`, `]`, `}` and `\n` are used to trigger on type formatting. The closing brackets are usually with complete expressions before cursor, while the line break can be in the end of either a complete expression (a single line call like `foo()`) or an incomplete expression to be continued in the next line (typical use case is pipelines ending with ggplot's `+` or magrittr's `%>%`)
To handle the case of `\n` …
=> Expression-level on-type-formatting

R/handlers-textsync.R, R/languageserver.R, tests/testthat/test-lintr.R
This PR disables lintr for files from temp root as suggested in #213.
Temp root is used instead of session temp dir because an interactive session may produce a file in temp for the editor to view (e.g. vscode-R allows user to call `View(func)` in a user session to view the function code in the editor. The file is located in the temp directory of the user session rather than the session running languageserver so they have different `tempdir()` but the same temp root `dirname(tempdir())`).
=> Disable lintr for temp files

DESCRIPTION, R/handlers-general.R, R/handlers-langfeatures.R, R/handlers-textsync.R, R/languageserver.R, R/link.R, R/utils.R, man/document_link_reply.Rd, man/is_package.Rd, tests/testthat/test-link.R
Closes #215 
Closes #216 
This PR imports `fs` to handle path-related issues.
* Replace `normalizePath()` with `fs::path_abs()` and `path.expand()` in `document_link_reply` so that symlinks are not resolved. If the link is a symlink, its target will be the symlink rather than the resolved real path.
* Add checking of `file:///` in `path_from_uri` to handle untitled document case where URI is `untitled:untitled-n`.
* Use `fs::path_has_parent` to correctly handle directory parent check since 
* Document URI and R `tempdir()` have different cases of disk drive in Windows.
* Document URI and rootPath may clash using `startsWith` (e.g. URI: `/home/user/project.R` and rootPath: `/home/user/project`)
* Fix document link since `path_to_uri` does not handle multiple paths.
* Add test cases for …
=> Fix resolving paths

R/handlers-general.R, R/handlers-langfeatures.R
Closes #219 
This PR checks `self$rootPath` on initialization and in `document_link_reply` so that it could handle the case where `rootPath` is `null`. `document_link_reply` is also fixed so that it could handle it when `rootPath` is `null` and document is untitled (`uri = "untitled:untitled-n"`).
=> Fix handling null rootUri

R/diagnostics.R
Closes #222 
This PR always uses `content` in `diagnose_file` and fixes one-line content so that it could correctly handle one-line content and untitled document.
We should avoid reading the file from the path of URI as long as we could get the content, or otherwise the unsaved or untitled document cannot be handled correctly.
=> Always use content in diagnose_file

DESCRIPTION, R/diagnostics.R, R/formatting.R, R/handlers-textsync.R, R/hover.R, R/languagebase.R, R/utils.R, tests/testthat/test-hover.R
Related to #125 
Follows up #229 
From https://github.com/REditorSupport/languageserver/pull/229#issuecomment-596041158.
>It seems that we could also remove dependency on stringr and use stringi regex functions directly since stringr uses stringi as backend but also imports glue which we have already removed the dependency, although this may not contribute much to reducing the installation size.
In this PR, most `stringr` calls are replaced with correponding `stringi` calls with less overhead.
Only `stringr::str_trunc` has not equivalent in `stringi` so I put a simplified version in `utils.R`.
=> Remove dependency on stringr

R/completion.R, R/handlers-langfeatures.R, man/completion_reply.Rd, man/workspace_completion.Rd
Follows up #168 
Closes #231 
This PR respects `snippetSupport` client capability so that function completion snippet like `foo($0)` is only used when client `snippetSupport = true`.
=> Respect client snippetSupport

DESCRIPTION, R/diagnostics.R, R/document.R, R/handlers-textsync.R, R/languageserver.R, R/task.R
Closes #245.
Originally, `throttle` is used to ensure that `run_tasks` is not called too frequently. However, if user input multiple characters in a short span of time (less than `t`) after some idle time, then only the first input triggers `run_tasks`, resulting in out-of-sync results. If user no longer changes the document, then the results will be out-of-sync forever.
This PR changes the throttle behavior of `TaskManager` so that each task gets a `time` at creation and the task manager only runs tasks older than `delay` seconds. Therefore, within `delay` seconds, the tasks are only replaced on user input. If any task is older than `delay`, then it will be executed. This ensures that the outcome is always sync when user stops changing the document.
Since diagnostics task, parse task are …
=> Run tasks with delay to reduce CPU usage on input

tests/testthat/test-null-root.R
This PR adds a test case for  6fff92f that closes #249.
=> Add a test case for null workspace root

R/utils.R
Closes #255 
This PR generalizes the Rmd code chunk pattern.
The following are valid Rmd code chunks supported by both RStudio and knitr.
* Spaces between backticks and `{r}`:
````r
``` {r}
x <- rnorm(100)
```
````
* More than 3 backticks:
`````r
````{r}
x <- rnorm(100)
````
`````
=> Generalize rmd chunk pattern

.github/workflows/main.yml, R/languageclient.R, R/languageserver.R, R/session.R, tests/testthat/helper-utils.R
Follows up #265.
The `pool_size` is altered to be more conservative for machines with fewer CPUs.
```
cpus<=3, pool_size=1
4<=cpus<=5, pool_size=2
cpus>=6, pool_size=3
```
=> Use more conservative pool_size

R/formatting.R, tests/testthat/test-formatting.R
Closes #264.
If the selection range has non-zero indentation, then a `apply_initial_indention` function injected to the formatting styles so that the top level expressions get the indentation.
For example, to format the code inside the the following function
```r
my_fun <- function() {
data <- query(
con ,
"select name, group, max(update_time) as max_time
from users
where date = ?date
group by group",
date = 20200601
)
x = 2
y = 3  
}
```
the code will be enclosed inside `{ ... } ` and then `apply_initial_indention` will apply the indention to all top-level expressions of the selection, then the curly braces are droped to get the formatted text.
The result is like 
```r
my_fun <- function() {
data <- query(
con,
"select name, group, max(update_time) as max_time
from users
where date = …
```
=> Fix range formatting handling initial indentation

R/formatting.R
As suggested at https://github.com/r-lib/styler/issues/641#issuecomment-636771120, `style$indention` is checked so that #268 is only applied to `scope >= "indention"`.
=> Use old behavior if formatting scope < indention

R/color.R, R/link.R, tests/testthat/test-link.R
Related #242 
This PR
* Fixes raw string handling in document link using `col1` and `col2` attributes of  `STR_CONST` (which are correct) and `parse()` to extract the right text.
* Ignores raw string in color provider to avoid incorrect replacement of color from color picker.
* Adds test cases of handling raw strings in document link.
=> Fix handling raw string in link and color

R/handlers-general.R, R/handlers-langfeatures.R, R/handlers-textsync.R, R/languageserver.R, R/utils.R, tests/testthat/test-unicode-path.R
it should fix some of the issues in #277.
We still need to fix the round trip issue
```
r$> a = "file:///foo/bar/中文.R"
r$> (b = languageserver:::path_from_uri(a))
[1] "/foo/bar/中文.R"
r$> (languageserver:::path_to_uri(b))
[1] "file:///foo/bar/%E4%B8%AD%E6%96%87.R"
```
=> make sure the path is UTF-8

R/symbol.R, tests/testthat/test-symbol.R
This PR enhances #186 by adding chunk symbols in addition to section symbols for R markdown documents.
Also requested at https://github.com/Ikuyadeu/vscode-R/issues/363.
For the following document,
````
---
title: new document
---
Hello, world!
```{r}
x <- rnorm(100)
y <- rnorm(100)
m <- lm(y ~ x)
fun1 <- function(x, y) {
x + y
}
```
```{r chunk-1}
x <- rnorm(100)
y <- rnorm(100)
m <- lm(y ~ x)
fun2 <- function(x, y) {
x + y
}
```
```{r chunk-2, eval=TRUE}
x <- rnorm(100)
y <- rnorm(100)
m <- lm(y ~ x)
fun3 <- function(x, y) {
x + y
}
```
```{r "chunk-3"}
x <- rnorm(100)
y <- rnorm(100)
m <- lm(y ~ x)
fun4 <- function(x, y) {
x + y
}
```
```{r 'chunk-4', eval=TRUE}
x <- rnorm(100)
```
```{r 'chunk-5, new test', eval=TRUE}
x <- rnorm(100)
```
```{r}
x <- 1
```
````
we could get the …
=> Rmd chunk symbol

R/completion.R
Close #285 
This PR uses `CompletionItem.sortText` defined in <https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_completion> to give different categories of completion items certain priorities.
The principle here is sorting by scope from local to global:
0. Function arguments
1. Scope symbols
2. Workspace symbols
3. Imported symbols
4. Constants, Packages, Namespace symbols
=> Use sortText in completions

README.md
The deprecated message from the `install-github.me` services. Replacing it with the `devtools` alternative.
```r
source("https://install-github.me/REditorSupport/languageserver")
```
=> Change dev version download script in the README

R/handlers-textsync.R
This pull request resolves issue #283.
It replaces `$` accessors with `[[` to prevent partial matching of `params$text` to `params$textDocument` when `text` is undefined.
Todo:
=> Fix for #283 - "unexpected '/'" on save

R/document.R, R/namespace.R, R/symbol.R, R/utils.R, R/workspace.R, tests/testthat/test-symbol.R
This PR adds all symbols to definitions so that it is easier to search symbols via document/workspace symbol search.
```r
func <- function(x, y) {
m <- x + y
n <- x * y
m + n
}
Person <- R6::R6Class("Person",
private = list(
name = NULL,
age = NULL
),
public = list(
initialize = function(name) {
private$name <- name
},
greeting = function() {
cat("Hello, my name is ", private$name, "!\n", sep = "")
}
))
person <- Person$new(name = "Somebody")
num <- 1
lgl <- TRUE
text <- "hello"
vec <- c(1, 2, 3)
lst <- list(
x = 1,
y = 2,
z = list(a = 1, b = 2)
)
var <- rnorm(100)
```
The above code has the following symbol outline:
Some function calls are specially treated to generate different kinds of document symbols. `c()`,`matrix()`, and `array()` creates Array symbol, `list()` creates Struct …
=> Support all symbols in definitions

R/document.R, R/namespace.R, R/workspace.R
Close #301
This PR respects the attached packages specified in user/system profile so that the initial auto-completion could include the package exported objects on startup.
=> Support startup library specified in profile

R/workspace.R
Follows up #295.
This PR makes go-to-definition work with cross-file global non-functions symbols.
=> Use isf=FALSE

DESCRIPTION, R/completion.R, R/document.R, R/hover.R, R/signature.R, R/utils.R
Close #304
This PR imports `roxygen2` and implements `convert_comment_to_documentation` where `roxygen2::parse_text()` is tried to parse comments as roxygen tags to provide structured documentation.
The information presented in hover contains all parsed roxygen tags presented in markdown format while only description is presented in completion resolve of symbol and function arguments and function signature, which is consistent with currently presented information provided by these providers.
Following is a screencast:
=> Convert roxygen comments to documentation

R/formatting.R
This PR disables on-type-formatting on both whitespace line and comment line.
In VSCode, the vscode-R auto inserts `#' ` on enter, i.e.
```
#' Press enter here and auto insert the following line
#' 
```
If formatting is perfomed, then the whitespace after `#'` is styled out, which is annoying in writing roxygen documentation.
=> Not trigger on-type-formatting on comment line

R/folding.R, tests/testthat/test-folding.R
This PR adds support of folding ranges for comments so that consecutive lines of comments that start with the same column can be folded.
```r
a <- 1
b <- 2
c <- 3
f <- function(x, y) {
x + y
}
```
The comments in the same folding ranges could be folded.
=> Support folding ranges for comments

R/color.R, R/link.R
Close #313.
For link provider, the string length is limited to 255 characters.
For color provider, the string length is limited from 3 (shorted color name, e.g. `red`) to 20 (longest color name, e.g. `lightgoldenrodyellow`).
=> Limit string length to provide color and link

R/utils.R
This PR is a minor fix of Rmd chunk patterns used to extract R code blocks to work with both of the following cases:
````
```{r}
x <- 1
```
```{R}
x <- 1
```
````
=> More robust rmd chunk pattern

R/folding.R, tests/testthat/test-folding.R
Close #316 
This PR make folding range provider only create folding ranges for multi-line expressions with `()`, `[]` and `{}`, and the folding range end is a line above the closing bracket so when the range is folded the closing bracket could be seen. Now the folding ranges are consistent with behavior of most other language servers.
```r
if (x > 0) {
x + 1
} else if (x < -1) {
x - 1
} else {
x
}
```
Before:
After:
And multi-line expressions not enclosed in a pair of brackets are no longer foldable. For example, a pipeline expression could no longer be folded as it is not enclosed in brackets.
```r
kable(dt, format = "html", caption = "Demo Table") %>%
kable_styling(bootstrap_options = "striped",
full_width = FALSE) %>%
add_header_above(c(" ", "Group 1" = 2, "Group 2[note]" = 2)) %>% …
```
=> Improve folding

R/completion.R, tests/testthat/test-completion.R
It is hard to provide accurate completion based on static code analysis in the following cases:
* Completion for R6 class members (#75)
* Completion for list or data.frame elements (#158)
* Completion for symbols in a pipeline (https://github.com/Ikuyadeu/vscode-R/issues/323)
This PR is an attempt to partially address these cases by providing completions from symbols that appear in the current document so that the symbols are recognized as texts that could be repeatedly used in the document, as demonstrated in the following images.
Since the token completion items have the lowest ranking, they won't interrupt normal completions but provide some help when the normal code analysis does not provide anything.
=> Add token completion

R/completion.R
Follows up #324 
This PR removed duplicate token completion items if a symbol is already provided by other completion providers.
=> Exclude existing completion items in token_completion

R/completion.R, R/definition.R, R/hover.R, tests/testthat/test-completion.R, tests/testthat/test-definition.R, tests/testthat/test-hover.R
Close #327 
`LEFT_ASSIGN`, `RIGHT_ASSIGN`, and `EQ_ASSIGN` are restrictive enough to limit the scope of the XPath selectors, so no need to specify their parent node.
=> Update xpaths to adapt to token change in parse data in R 4.0

R/workspace.R
In the R directory, some packages have the `sysdata.rda` file (see https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-subdirectories for reference), which tries to get loaded on_initialized. This PR proposes to skip that file from `load_all()`.
=> Do not load sysdata.rda

R/capabilities.R, R/definition.R, R/handlers-langfeatures.R, R/languageserver.R, R/references.R, README.md, tests/testthat/helper-utils.R, tests/testthat/test-references.R
Close #336 
This PR implements a simple [referencesProvider](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references) based on the current definitionProvider.
1. Find the definition of the requested token.
2. Find all symbols with the same text of the requested token in all documents in workspace (`R/*.R` for package or otherwise open R documents in non-package workspace)
3. Find the definition of each symbol in each document.
4. Regard the symbol as a reference if its definition is identical to that of the requested token.
This PR also provides test cases for the referencesProvider (also based on test cases of the definitionProvider).
=> Implement referencesProvider

R/definition.R, R/hover.R, tests/testthat/test-definition.R, tests/testthat/test-hover.R
Close #341 
This PR improves the XPaths of definition and hover so that the XPaths ensure that the requested token is not included in the value expression of the assignment, i.e. RHS of left assignment and equal assignment and LHS of right assignment.
Then the definition and hover providers will regard line 1 as the definition of token `test` in line 2 on RHS of the assignment:
```r
test <- 1
test <- test + 1
```
=> Fix checking symbol on rhs of assignment expression

R/hover.R, R/workspace.R, tests/testthat/test-hover.R
Close #343 
This PR makes hover on non-function symbols across multiple files work.
=> Fix hover on non-function symbol

R/hover.R, tests/testthat/test-hover.R
Close #345 
This PR fixes the XPath to find if the last definition is a function and adds some test cases.
=> Fix hover func arg

R/capabilities.R, R/handlers-general.R, R/handlers-langfeatures.R, R/languagebase.R, R/languageserver.R, R/rename.R, README.md, tests/testthat/helper-utils.R, tests/testthat/test-rename.R
Close #337 
This PR implements [prepareRename](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareRename) and [renameProvider](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_rename) based on the referenceProvider implemented by #338 by transforming the references into a [WorkspaceEdit](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspaceEdit).
=> Implement renameProvider

R/handlers-textsync.R
Close #348 
If the workspace is not a package, closing a document in workspace will also remove its diagnostics.
=> Remove diagnostics of closed files in non-package workspace

README.md
Updates README because the original didn't show that coc could be configured entirely from `coc-settings.json`.
=> Update coc help in README

NEWS.md, R/document.R, tests/testthat/test-symbol.R
Closes #362 
```r
x <- 1
y <- "a"
z <- function() {
'hello'
}
delayedAssign("d1", 1)
delayedAssign(value = function() 2, x = "d2")
base::delayedAssign(value = "3", "d3")
var <- "d4"
delayedAssign(var, 4)
delayedAssign(("d5"), var)
makeActiveBinding("a1", function() 1, environment())
makeActiveBinding(function() "2", sym = "a2")
base::makeActiveBinding(fun = function() stop("3"), sym = "a3")
makeActiveBinding(("a4"), function() 1, environment())
assign(value = "1", "assign1")
```
=> Recognize symbols created by delayedAssign / assign / makeActiveBinding

tests/testthat/test-symbol.R
I think using `expect_setequal()` may be better for these testing cases.
=> use expect_setequal() may fit better

R/hover.R, tests/testthat/test-hover.R
This PR adds hover to function symbol formals so that it is easier to see the documentation of the function argument on hover, especially when the function has many arguments.
```r
#' @param var1 test
#' @param var2 test2
#' @param var3 sum of test and test2
test <- function(var1 = 0, var2 = 1,
var3 = var1 + var2
) {
var1
var2
}
```
```r
#' @param index number
res <- lapply(1:10, function(index) {
index + 1
})
```
=> Add hover to function symbol formals

R/signature.R
With latest vscode-languageclient 7.0.0 used in vscode-r-lsp 0.1.14, the following code does not trigger SignatureHelp:
```r
fun <- function(x, y) {
x + y
}
fun(
```
It looks like`documentation === null` is no longer accepted by  vscode-languageclient 7.0.0. The [LSP](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_signatureHelp) says the following
```typescript
documentation?: string | MarkupContent;
```
looks like `documentation` could not be `null`.
This PR is a simple fix and it works with latest vscode-r-lsp now.
=> Use empty string instead of NULL as default signature doc

R/capabilities.R
I think it makes sense to add `(` as a completion trigger character when user types a function call it will show the arguments in completion and signature help at the same time.
=> Add '(' to completion trigger characters

R/completion.R, tests/testthat/test-completion.R
I think it looks better if the order of argument completion items is consistent with the function formals.
=> Preserve argument order in argument completion

R/completion.R
This PR improves the token completion with the following changes:
1. Since #369 allows `(` to trigger completion to in accompany with https://github.com/Ikuyadeu/vscode-R/pull/530, the current token_completion may produce too many symbols once `(` triggers completion. This PR makes token_completion only show symbols after `$` and `SYMBOL_SUB` symbols like `foo` in `mutate(foo = bar)` when trigger `token` is empty (e.g. `foo$` and `fun(`), which are the most frequent ways to introduce new data variables.
2. If `token` is not empty, then all symbols from the document that start with `token` are searched, which is the original method.
This makes it possible to work with the following examples:
```r
library(data.table)
library(dplyr)
library(tibble)
tbl1 <- tibble(
Name = c("Product1", …
```
=> Improve token completion

R/capabilities.R
Having experienced the #369, using `(` as a completion trigger character is in most cases too eager: once the completion is triggered, the new typed character won't trigger the computation of completions in a while. In practice, this will usually disable many other completion items or leave no change for them to show up.
Therefore, I'd like to revert that change by removing `(` from completion trigger characters.
=> Remove '(' from completion trigger chars

DESCRIPTION, R/utils.R, R/workspace.R
This PR tries to improve the quality of function documentation in hovers.
To test:
Hover e.g. over these expressions:
``` r
is.character()
is.na()
is.null()
```
~~Known issues:~~
~~Some special characters (e.g. the quotes in the documentation for `is.na`) get rendered incorrectly.~~
(Edit: fixed by specifying the encoding to be utf-8)
=> Improve hover for function docs

R/completion.R, tests/testthat/test-completion.R
This PR adds arg completion for `options()` calls so that it is easier to complete options.
Note that if user code calls e.g. `library(data.table)`, and the new options defined in `data.table` will also appear in the options arg completion since the package is also loaded by languageserver.
=> Options completion

R/utils.R, R/workspace.R
Modifies the header of help hovers to remove the first line.
Information about the package is moved to the first proper header instead.
=> Make headers in help hover look prettier

R/capabilities.R, R/handlers-langfeatures.R, R/languageserver.R, R/link.R, R/utils.R, README.md, tests/testthat/helper-utils.R, tests/testthat/test-link.R
Closes #391 
The main reason not to use file extension is that there are too many text file extensions so that it might not be a good idea. To keep user from following a link to a large file that might freeze the editor, we only need to avoid providing links to large files.
This PR checks file size at `documentLink/resolve` so that large files won't be provided links. By default, the file size limit is 16MB. User could customize it via `options(languageserver.link_file_size_limit = bytes)`.
The reason to check file size at resolve stage is that we could let the user know that the file exists via editor text decoration (e.g. text underlined in vscode).
=> Limit link file size

R/completion.R, R/utils.R, tests/testthat/test-completion.R
Closes #401.
This PR uses `grep(ignore.case=TRUE)` to provide case-insensitive and partial matching completion items to replace the current case-sensitive, exact-matching-from-start filtering.
=> Provide case-insensitive completion

R/utils.R, man/sanitize_names.Rd
This PR updates `sanitize_names` so that symbols starting with `._` (like shown in the following) are removed from namespace and won't be present in the completions.
=> Remove symbols starting with `._` from namespace

src/search.c
=> fix a segfault issue

DESCRIPTION, R/formatting.R, man/style_text.Rd
Closes #400.
This PR uses the latest styler `base_indention` and removes the old hacking way to add indention.
I think we could wait until https://github.com/r-lib/styler/pull/764 is merged upstream so that this PR could be merged too.
We'll update the minimum version of styler in `DESCRIPTION` if a new version (probably v1.4.1) is released to CRAN.
=> Use styler base_indention

src/fsm.c, tests/testthat/test-search.R
close #410 
- need to cherrypick to release/0.3.10
=> fix raw string detection

R/completion.R, R/utils.R
Closes #412 
This PR improves the performance of completion by limiting the max number of completions to return to the client and utilizing the `isIncomplete` feature.
If the completion list contains more than `nmax` (by default, 200) items, then the list is sorted by whether it starts with `token` and the `sortText` of the item, and the top `nmax` items are returned with `isIncomplete = TRUE` so that subsequent keystrokes will still trigger completion requests until the completion list is narrowed down to no greater than `nmax`.
This largely avoids too much traffic from the response to the completion request triggered by the first keystroke, which could potentially match too many results.
Old behavior (on my machine working in languageserver project):
1. Type `a`
2. 1619 matches returned …
=> Faster completion

R/definition.R, R/handlers-langfeatures.R, R/link.R, R/utils.R, man/definition_reply.Rd, man/document_link_reply.Rd, tests/testthat/test-definition.R
Closes #415 
This PR makes `STR_CONST` token which is either an absolute path or a path relative to workspace `rootPath`.
It also checks if the file is a text file by reading its first 1000 bits  into a raw vector using `readBin` and see if ~~`rawToChar` succeeds~~ it is a text file by detecting its text encoding with `{stringi}` functions.
=> Definition provider works with file path

R/definition.R
It should fix the random definition bug introduced [earlier](https://github.com/REditorSupport/languageserver/pull/409#issuecomment-822625528).
@renkun-ken
=> definition fix

DESCRIPTION, NEWS.md
=> bump to 0.3.10

R/handlers-general.R, R/handlers-protocol.R, R/handlers-workspace.R, R/languageserver.R, R/log.R
=> support trace in InitializeParams

R/formatting.R
Closes #430 
This PR changes the completer from `0` to `f()` so that the pipe syntax could be supported.
=> Use a function call as the completer in on-type-formatting

R/completion.R, R/definition.R, R/hover.R, R/signature.R
Closes #427 
This PR extends the XPath expressions where `FUNCTION` is used to also support `OP-LAMBDA`.
=> Lambda support

DESCRIPTION, R/diagnostics.R, README.md
> I just realized that there is no roadmap for the release of new version of lintr. Perhaps we should include your original trick of checking the text parameter for now? Otherwise we won't know how much time they need to make a new release.
related: #284 
I have decided to use `packageVersion` at the end.
=> check if lintr is new enough

R/document.R, R/zzz.R, tests/testthat/test-completion.R, tests/testthat/test-symbol.R
Closes #257
Closes #426 
Closes #451
This PR introduces customizable ~~unscoped~~ parser hook functions ~~and library functions~~ so that the following code could be supported:
```r
suppressPackageStartupMessages({
pacman::p_load(dplyr)
})
```
~~The unscoped functions (e.g. `try`, `suppressPackageStartupMessages`, `system.time`) evaluate an expression in its calling environment as if the `expr` is directly evaluated but with some other things done.~~
~~The library functions (e.g. `library`, `require`) are a list of functions recognized as equivalent with `library`. An example is `pacman::p_load`.~~
~~User could add more functions via the option `languageserver.unscoped_functions` and `languageserver.library_functions` respectively in `.Rprofile`.~~
The `parse_expr` function is rewritten …
=> Support unscoped functions and library functions

DESCRIPTION, README.md
Closes #457 
This PR makes the package require styler >= 1.5.1 so that the default cache root path (`~/.cache/R/R.cache`) is global to the user rather than per session. No prompt required to use a global cache root. Therefore, there is no need to mention the cache issue in the README.
=> Require styler >= 1.5.1

DESCRIPTION, NEWS.md
Hooray!. Thanks @renkun-ken for the latest commits!
=> bump to 0.3.11

R/handlers-langfeatures.R, R/utils.R, tests/testthat/helper-utils.R, tests/testthat/test-completion.R, tests/testthat/test-definition.R, tests/testthat/test-link.R, tests/testthat/test-workspace.R
Closes #460 
This PR makes handling null workspace folder and untitled document with the following logic:
1. If the workspace folder is not null, then use it as the root path.
2. Otherwise, if path from uri is not empty, use the directory of the path.
3. Otherwise, the uri is not a `file://` uri, then use the working directory of the language server process.
=> Fix handling null workspace folder and untitled document

R/completion.R, R/definition.R, R/document.R, R/hover.R, R/signature.R, tests/testthat/test-completion.R, tests/testthat/test-definition.R, tests/testthat/test-hover.R, tests/testthat/test-signature.R
Closes #463 
Hovering on the left part of a symbol might capture the symbol token with `document$detect_token()` while the XPath captures the token on the left of the cursor, e.g. an operator, and thus shows the workspace definition of the captured token rather than the scope definition.
This PR:
* Ignores the operator captured by XPath.
* Replaces all `\t` with a space in `parse_document()` to make the width of tab consistent between LSP and `getParseData()`.
* Improves the XPaths of hover, definition, signature, and scope completion to support code with semi-colons where nested `exprlist` nodes appear in the XML syntax tree.
=> Fix several bugs

R/hover.R, tests/testthat/test-hover.R
Closes #466 
This PR fixes the XPath to extract function signature from the definition with `EQ_ASSIGN` by matching `expr/LEFT_ASSIGN` and `expr_or_assign_or_help/EQ_ASSIGN` in the XML parse tree.
=> Fix hover on function defined with `EQ_ASSIGN`

DESCRIPTION
Closes #470 
This PR removes `desc` from `Imports` as it is no longer used anywhere.
=> Remove desc from imports

DESCRIPTION, R/namespace.R, R/utils.R, R/workspace.R
Closes #468 
This PR implements an internal `get_help()` to produce HTML or text from Rd. Then, repr is no longer imported.
=> Use internal `get_help` instead of repr

R/handlers-general.R, R/handlers-protocol.R, R/handlers-workspace.R, R/languagebase.R, R/log.R, R/settings.R
Closes #497 
This PR unpublishes diagnostics of all workspace documents when diagnostics is disabled from client settings.
Also, this PR corrects the signature of `protocol_set_trace` to `protocol_set_trace(self, params)`. This handler turns on/off `debug` previously, which might cause conflicts with `r.lsp.debug` since if it is `true` but the language server trace is not turnoed on, then on the server side the debug will be enabled on startup but then disabled due to `setTrace` notification says `off`.
I add a new `trace` setting parallel with `debug` as well as `logger$trace` so that they have no conflicts.
`logger$info` works if either `debug` or `trace` is on, and `logger$trace` only works if `trace` is on.
=> Unpublish diagnostics when disabled

R/definition.R, R/link.R, R/utils.R
Due to https://github.com/r-lib/fs/issues/269, the known limitation of `fs` functions, it might make sense to only call `fs::path_abs` only with existing files so that long strings that are not file paths are not passed to the function.  In #502, it seems that even as we filter the string length, it might be possible that some long strings will still cause a problem. This PR checks the strings first and only call `fs::path_abs()` with existing file paths.
Here, the purpose we use `fs::path_abs()` is that we need to get an absolute path but not follow the symlinks.
=> Only call `fs::path_abs` with existing files

R/formatting.R
Closes #462 
In document formatting, a trailing new line is ensured in the end of the new text.
=> Document formatting ensures trailing empty line

R/diagnostics.R, R/document.R, R/handlers-textsync.R, R/handlers-workspace.R, R/utils.R, R/workspace.R, tests/testthat/helper-utils.R, tests/testthat/test-completion.R
Closes https://github.com/REditorSupport/vscode-R/issues/930
Closes #510 
This PR supports the unused field `languageId` of [`TextDocumentItem`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocumentItem) so that any file with `languageId == 'rmd'` is treated as rmd file. If `languageId` is not provided on document open, then it will fallback to using file extension to determine if it is rmd.
=> Respect document `languageId`

R/namespace.R, tests/testthat/test-completion.R
Currently, we use `formals()` to extract function arguments for completion. However, it does not work with primitive functions such as `sum` and `seq.int` by returning `NULL`.
Fortunately, `formals(args(primitive_fun))` works. This PR fixes this.
=> Support arg completion for primitive functions

DESCRIPTION, NEWS.md, R/utils.R, inst/lua/html-to-markdown.lua
=> convert the table of arguments to the sections of arguments with Lua filter

.github/dependabot.yml, .github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/rcmdcheck.yml, .github/workflows/tagbot.yml
It seems that the versions of `r-lib/actions/setup-r` and others are out of date.
Setting up dependabot will detect new releases and create PRs to help keep track of the latest versions.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
=> Update GItHub Actions version

src/search.c, tests/testthat/test-search.R
=> do not pop the unbalance brackets in the current row

README.md
Closes #536 
I set up a [repo](https://github.com/REditorSupport/universe) to contain the configuration of our [r-universe](https://reditorsupport.r-universe.dev) and updated README accordingly.
The repo that runs Github Actions to update and build the unvierse is <https://github.com/r-universe/reditorsupport>.
=> R universe

src/reader.c
@milanglacier
Could you test this PR? I am thinking that `read` may return -1 in some cases, so the output is duplicated.
close #368
=> read may return -1 on error

tests/testthat/test-unicode-path.R
To fix the test failure for R 4.2 on Windows.
@renkun-ken, please take a look.
=> R 4.2 supports Unicode on Windows

tests/testthat/test-unicode-path.R
I believe this simple expression can be used because the `numeric_version` class object can compare version numbers separated by periods.
=> minor refactoring: simplify the version number handling

R/utils.R
=> fix NA introduced into position

R/completion.R, R/handlers-langfeatures.R
This PR adds support for [completionItemLabelDetails](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItemLabelDetails) by showing function signature in completion list on resolve.
=> Support completion item labelDetails

R/diagnostics.R, R/handlers-workspace.R
Closes https://github.com/REditorSupport/vscode-R/issues/1196
If the client opens a document before the language server receives settings from the client, diagnostics will be triggered (which is default). If diagnostics is disabled, `diagnostics_callback` will still publish the diagnostics results, which is undesirable.
This PR corrects this behavior by checking diagnostics settings again before publishing results. At this point, it is most likely for the server to have already received the settings from the client.
=> Drop diagnostics on callback if disabled

DESCRIPTION, NEWS.md, R/diagnostics.R, src/languageserver.c, src/reader.h
Will merge after CRAN accepts the submission.
=> bump to v0.3.14

R/signature.R
Discovered in https://github.com/helix-editor/helix/issues/5023, `languageserver` was emitting a `-1` to a field that has the type `uinteger`. 
Specifically, a negative `activeSignature` was being emitted by default when no signatures are provided to a `signatureHelp` request. The spec covers cases where an "out of range" value is emitted, but I don't think this is intended to cover negative values.
As `activeSignature` is an optional field, I changed it so that the default is to leave the field unspecified. This has resolved the issue in the helix text editor's LSP listener.
=> Avoid emitting a negative activeSignature

R/code_action.R, tests/testthat/test-code-action.R
Code actions are improved to support disable relevant linters when diagnostics are present.
When a code action of disabling a linter is chosen, its name will be added after `# nolint:` directive if exists.
=> Disable linters actions

R/namespace.R, tests/testthat/test-completion.R
Closes #590 
`objects(ns)` does not include all exports such as `rvest::read_html()` (from `xml2`) and `purrr:set_names()` (from `rlang`). This PR makes the `Namespace` object include all namespace objects and all exports (not necessarily live in the same namespace).
=> Include all exports in namespace objects

README.md
This simple PR adds a link to the [R-Nova](https://github.com/jonclayden/R-Nova) extension for [Nova](https://nova.app) to the README, which uses the package for language server support in that editor.
=> Add link to R-Nova extension for Nova

R/section.R, tests/testthat/test-symbol.R
Now '```{r, chunklabel}' is recognized.
=> Fix regex pattern to match chunk label after comma

R/utils.R
Looks like the vscode-notebook-cell uris look like the following on different platforms:
```
```
=> Fix path_from_uri

R/diagnostics.R, R/utils.R
=> make sure column is defined

R/section.R, tests/testthat/test-folding.R
Sorry for my bad coding style which may prevent the understanding, In this commit I also tried to add more notes comment.
But the main purpose is to fix https://github.com/REditorSupport/vscode-R/issues/1076
Binary operations are collapsed
=> Enable the folding of binary operations

NEWS.md, R/folding.R, R/section.R, R/settings.R
=> Add `nline_to_break_succession` as option (#643)
